// Generated by https://quicktype.io

export interface Order {
  id: string;
  strategy_id: string;
  is_buy: boolean;
  is_future: boolean;
  is_limit: boolean;
  limit_price: null;
  symbol: string;
  symbol_id: string;
  amount: number;
  status: Status;
  reception_date: string;
  execution_id: string;
  execution_price: number;
  execution_date: string;
  response: null;
}

// 'open', 'closed', 'canceled', 'expired', 'rejected', 'failed'

export enum Status {
  Open = "open",
  Closed = "closed",
  Canceled = "canceled",
  Expired = "expired",
  Rejected = "rejected",
  Failed = "failed",
}
