// Generated by https://quicktype.io

export interface StrategySchema {
  account_id: string;
  name: string;
  symbol: string;
  symbol_id: string;
  is_future: boolean;
  leverage: number;
  entry_size: number;
  is_percentage: boolean;
  capital: number;
}

// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface Strategy {
  id: string;
  account_name: string;
  name: string;
  webhook_id: string;
  webhook_key: string;
  symbol: string;
  symbol_id: string;
  is_future: boolean;
  leverage: number;
  entry_size: number;
  is_percentage: boolean;
  capital: number;
  creation_date: string;
  invested_7_days: number;
  income_7_days: number;
  invested_7_days_percent: number;
  income_7_days_percent: number;
  nb_orders_7days: number;
}
