// Generated by https://quicktype.io

export interface StrategySchema {
  account_id: string;
  name: string;
  symbol: string;
  symbol_id: string;
  is_future: boolean;
  leverage: number;
  entry_size: number;
  is_percentage: boolean;
  capital: number;
}

// Generated by https://quicktype.io

export interface Strategy {
  id: string;
  account_id: string;
  name: string;
  webhook_id: string;
  webhook_key: string;
  symbol: string;
  symbol_id: string;
  is_future: boolean;
  leverage: number;
  entry_size: number;
  is_percentage: boolean;
  capital: number;
  orders: any[];
}
