// Generated by https://quicktype.io

export interface IUser {
  id: string;
  client_id: null;
  email: string;
  password: null;
  first_name: string;
  last_name: string;
  birthday: string;
  created_at: string;
  expiration_date: null;
  subscription_plan: null;
  is_actif: boolean;
  accounts: any[];
}
