// Generated by https://quicktype.io

import { Exchange } from "./exchange";

export interface IWallet {
  id: string;
  name: string;
  exchange: Exchange;
  key_id: string;
  key: string;
  balance: number;
  currency: string;
  user_id: string;
  strategies: any[];
  created_at: string;
}
